# prettier-ignore
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-sre-agent.fullname" . }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
