apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-agent
  namespace: sre-system
  labels:
    app: sre-agent
    version: v3.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sre-agent
  template:
    metadata:
      labels:
        app: sre-agent
        version: v3.0.0
    spec:
      serviceAccountName: sre-agent
      containers:
      - name: sre-agent
        image: sre-agent:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: sre-agent-secrets
              key: azure-openai-endpoint
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: sre-agent-secrets
              key: azure-openai-api-key
        - name: K8S_IN_CLUSTER
          value: "true"
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8000"
        - name: PROMETHEUS_URL
          value: "http://prometheus-operated.observability:9090"
        - name: LOKI_URL
          value: "http://loki.observability:3100"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/detailed
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: sre-agent
  namespace: sre-system
  labels:
    app: sre-agent
spec:
  type: ClusterIP
  selector:
    app: sre-agent
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-agent
  namespace: sre-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sre-agent
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - services
  - events
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sre-agent
subjects:
- kind: ServiceAccount
  name: sre-agent
  namespace: sre-system

---
apiVersion: v1
kind: Secret
metadata:
  name: sre-agent-secrets
  namespace: sre-system
type: Opaque
stringData:
  azure-openai-endpoint: "REPLACE_WITH_YOUR_ENDPOINT"
  azure-openai-api-key: "REPLACE_WITH_YOUR_API_KEY"
