name: Helm checks

on:
  pull_request:
    paths:
      - "charts/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.4

      - name: Install yamllint
        run: pip install yamllint

      - name: Check YAML formatting and validity (only pure YAML)
        run: |
          yamllint charts/**/values.yaml
          yamllint charts/**/Chart.yaml

      - name: Lint all Helm Charts
        run: |
          for chart in charts/*; do
            helm lint "$chart"
          done

      - name: Scan all Helm charts with kube-linter
        uses: stackrox/kube-linter-action@v1
        with:
          directory: charts
