name: Agent checks

on:
  push:
    paths:
      - "agent/**"
  pull_request:
    paths:
      - "agent/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install lint dependencies
        run: |
          pip install black==23.9.1 ruff==0.1.9

      - name: Check formatting with Black
        run: black --check agent/
        continue-on-error: true

      - name: Lint with Ruff
        run: ruff check agent/ --select E,F,I,B
        continue-on-error: true
