name: Agent checks

on:
  pull_request:
    paths:
      - "agent/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install black==25.9.0 ruff==0.13.2 bandit==1.8.6

      - name: Format check (Black)
        run: black --check agent/
        continue-on-error: true

      - name: Lint with Ruff
        run: ruff check agent/ --select E,F,I,B
        continue-on-error: true

      - name: Security scan (Bandit)
        run: bandit -r agent/
        continue-on-error: true
